cache:
  yarn: true
git:
  depth: false
language: node_js
node_js:
  - 10
notifications:
  email:
    on_success: never
services:
  - docker
  - postgresql
  - rabbitmq

addons:
  sonarcloud:
    organization: nerddan-github
    token:
      secure: $SONAR_TOKEN

script:
  - sonar-scanner
